version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - static_volume:/app/static
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - USE_SPACES=${USE_SPACES}
      - SPACES_ACCESS_KEY=${SPACES_ACCESS_KEY}
      - SPACES_SECRET_KEY=${SPACES_SECRET_KEY}
      - SPACES_BUCKET_NAME=${SPACES_BUCKET_NAME}
      - SPACES_REGION=${SPACES_REGION}
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost/api
      - HOST=0.0.0.0
    depends_on:
      - nginx

  nginx:
    build: ./backend/nginx
    volumes:
      - static_volume:/app/static
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  static_volume: