version: '3.8'

services:
  backend:
    build: .
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    env_file:
      - ./.env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - USE_SPACES=${USE_SPACES}
      - SPACES_ACCESS_KEY=${SPACES_ACCESS_KEY}
      - SPACES_SECRET_KEY=${SPACES_SECRET_KEY}
      - SPACES_BUCKET_NAME=${SPACES_BUCKET_NAME}
      - SPACES_REGION=${SPACES_REGION}
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8000"

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/staticfiles
    ports:
      - 1337:80
    depends_on:
      - backend

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  static_volume: 