# Generated by Django 4.2 on 2024-12-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='level_required',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='project',
            name='pdf_file',
            field=models.FileField(upload_to='projects/pdfs/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='points_required',
            field=models.IntegerField(),
        ),
    ]
