# Generated by Django 4.2 on 2024-12-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_level_required_alter_project_pdf_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='points_required',
            field=models.IntegerField(default=1),
        ),
    ]
