# Generated by Django 4.2 on 2024-12-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='approval_code',
        ),
        migrations.AlterField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=1),
        ),
    ]
